- name: play1
  hosts: [servers]
  vars:
    package_name: nginx
    package_state: latest

  gather_facts: no

  tasks:
    - name: Install Nginx
      apt:
        name: "{{ package_name }}"
        state: "{{ package_state }}"
   
    