- name: play1
  hosts: [servers]
 
  gather_facts: yes

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: latest
      register: result

    - name: Debug
      debug:
        var: result

    - name: Restart
      sysvinit:
        name: nginx
        state: restarted
      when: result.changed or not result.failed