- name: Play1
  hosts: [servers]
  gather_facts: no

  tasks:
    - name: Different actions
      apt:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop:
        - { name: nginx, state: present }
        - { name: curl, state: absent }
        - { name: ssh, state: latest }
        - { name: sudo, state: present }