- name: play1
  hosts: [servers]
  gather_facts: no

  tasks:
    - name: Install Nginx
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - nginx
        - curl
        - ssh
        - sudo 

    