- name: play1
  hosts: [servers]
  gather_facts: no
  tasks:
    - name: Ping host
      ping:
    - name: Update package cache
      apt:
        update_cache: true
    - name: Install Nginx
      apt:
        name: nginx
        state: present

        


    