- name: play1
  hosts: [servers]
  gather_facts: no

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      tags:
        - update

    - name: Install Nginx
      apt:
        name: nginx
        state: latest
      tags:
        - install

    