- name: play1
  hosts: [servers]
 
  gather_facts: yes

  vars:
    restart: true

  tasks:
    - name: Install nginx or apache2
      apt:
        name: "{{ 'nginx' if ansible_facts['distribution'] == 'Ubuntu' else 'httpd' }}"
        state: latest
      when: ansible_facts['distribution'] in ['Ubuntu', 'CentOS']

    - name: Restart nginx or httpd
      sysvinit:
        name: "{{ 'nginx' if ansible_facts['distribution'] == 'Ubuntu' else 'httpd' }}"
        state: restarted
      when: (ansible_facts['distribution'] == 'Ubuntu' and restart) or (ansible_facts['distribution'] == 'CentOS' and restart)